### ISSUE TITLE
Defang cd init with previous s3 bucket

### ISSUE THREAD

**Issue by raphaeltm** [DefangLabs/defang#358]
If I ran `defang cd teardown` previously, I might want to re-add it with the existing state/s3 bucket. It would be useful to have something like `defang cd init <bucket name>`

**Comment by defangdevs** [comment]
This is directly relevant to #2192: because the CD bucket is CloudFormation-auto-named and retained on stack delete, `defang cd teardown` + re-bootstrap mints a fresh bucket and strands the old one (8 orphaned buckets found in one account). Adopting the previous bucket on init (this issue) would fix the churn. Might be worth reopening.
