### ISSUE TITLE
Config vals should override values set in compose.yaml 

### ISSUE THREAD

**Issue by raphaeltm** [DefangLabs/defang#449]
If I run `defang config set BOARD_PASSWORD` and I have the following:

```
    environment:
      - BOARD_PASSWORD=devpassword
```

The value from config should be prioritized.

**Comment by lionello** [comment]
This is not trivial, since we need to know at deployment time which variables are from config and which ones are from env. It's not possible, for example, to add a new config var after deployment, it would not get picked up. What's possible is that during deployment we issue a warning if there's a value in the compose file for a var that's also in config.

**Comment by raphaeltm** [comment]
I think telling the user they would need to redeploy is fine. I think it would be nice to have some "UI" elements in the logs during deployment that outline how the deployment is going to run (i.e. config vals overriding env vars). Something like the preview that pulumi displays when you run it: just a simple visualization of what's going to happen.
